services:
  nest-app:
    image: artemzatula/home-library-service
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - db
    command: npm run start:dev
  
  db:
    image: postgres
    restart: always
    volumes:
      - postgres-db:/data/db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres-db: